// This is the template for ipfixidmapping, all lines until the marker will be removed before output
// +build ignore

//***GENERATEMARKER***
//Generated by generateipfixidmapping.go using ipfixidmapping_template
//Generation timestamp: {{.TimeStamp}} 
//Do not edit manually, run go generate
package ipfixmessage

import (
	"fmt"
)

// NewFieldValueByID returns an empty FieldValue that matches the enterprise id and element id
func NewFieldValueByID(enterpriseid int, elementid int) (FieldValue, error) {
	switch enterpriseid {
{{range $_, $enterpriseid := .EnterpriseOrder}}
case {{$enterpriseid}}: // {{index $.Sources $enterpriseid}}
{{$elements := (index $.Elements $enterpriseid)}}
    switch elementid { {{range $_, $elementid:= (index $.ElementsOrder $enterpriseid)}}
        case {{$elementid}}:
        return &{{(index $elements $elementid).GoFieldValue}}{}, nil // {{(index $elements $elementid).Name}}{{end}}
        default:
           return nil,NewError(fmt.Sprintf("No such element: E%did%d",enterpriseid,elementid),ErrCritical)
    }
{{end}}
	default:
		return nil, NewError(fmt.Sprintf("No such element: E%did%d", enterpriseid, elementid),ErrCritical)
	}
}

// FieldLengthByID returns the default length that matches the enterprise id and element id
func FieldLengthByID(enterpriseid int, elementid int) (uint16, error) {
	switch enterpriseid {
{{range $_, $enterpriseid := .EnterpriseOrder}}
case {{$enterpriseid}}: // {{index $.Sources $enterpriseid}}
{{$elements := (index $.Elements $enterpriseid)}}
    switch elementid { {{range $_, $elementid:= (index $.ElementsOrder $enterpriseid)}}
        case {{$elementid}}:
        return {{(index $elements $elementid).GoFieldLength}}, nil // {{(index $elements $elementid).Name}}{{end}}
        default:
           return 0,NewError(fmt.Sprintf("No such element: E%did%d",enterpriseid,elementid),ErrCritical)
    }
{{end}}
	default:
		return 0, NewError(fmt.Sprintf("No such element: E%did%d", enterpriseid, elementid),ErrCritical)
	}
    return 0,nil
}

// FieldDescriptionByID returns the given semantic description that matches the enterprise id and element id
func FieldDescriptionByID(enterpriseid int, elementid int) (string, error) {
	switch enterpriseid {
{{range $_, $enterpriseid := .EnterpriseOrder}}
case {{$enterpriseid}}: // {{index $.Sources $enterpriseid}}
{{$elements := (index $.Elements $enterpriseid)}}
    switch elementid { {{range $_, $elementid:= (index $.ElementsOrder $enterpriseid)}}
        case {{$elementid}}:
        return "{{(index $elements $elementid).Name}}", nil{{end}}
        default:
           return "",NewError(fmt.Sprintf("No such element: E%did%d",enterpriseid,elementid),ErrCritical)
    }
{{end}}
	default:
		return "", NewError(fmt.Sprintf("No such element: E%did%d", enterpriseid, elementid),ErrCritical)
	}
    return "",nil
}